homework3
kessydy/Homework pull request #3
Opened 2024-09-18 16:46 UTC by kessydy

Как я поняла, нужно всё уместить в один класс. Было сложно. Но что-то вышло)

2024-09-19 07:46 UTC, PavelIvanouski requested changes

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +        switch (numberOfMonth) {
красивее будет используя ->

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +    private static int getThreeDigitNumber() {
зачем два сканера? можно один везде использовать

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +        if ((number > 999) || number < 100) {
проверку можно вынести в отдельный метод - она выполняется в каждой задаче

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +            System.out.println("The full number is: " + (fullNumber[0] * 100) + "+" + (fullNumber[1] * 10) + "+" + fullNumber[2]);
этот вывод в консоль можно перенести в метод getFullThreeDigitNumber, чтобы этот метод конкретно решал задачу (проверял и выводил ответ), а так часть логики задачи в методе getFullThreeDigitNumber и часть в main методе

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +            System.out.println("The parity of number " + number + " is " + parityOfNumber);
тоже самое что и для getFullThreeDigitNumber

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +            System.out.println("The number " + symmetry);
тоже самое что и для getFullThreeDigitNumber

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +            System.out.println("The triangle " + checkTriangle);
тоже самое что и для getFullThreeDigitNumber

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +        System.out.println(checkMonth);
тоже самое что и для getFullThreeDigitNumber

2024-09-19 07:46 UTC, PavelIvanouski commented on src/by/it_academy/homework3/Homework3.java
> +        int number1 = scanNumber();
ввод числа тоже в метод перенести нужно. чтобы в итоге из main вызывался нужный метод (зачада) и выводился ответ

2024-09-20 08:29 UTC, kessydy commented
Нечаянно удалила последний комментарий. Так и не смогла вывести Сканер в отдельный метод. Постаралась учесть правки)

2024-09-22 09:17 UTC, PavelIvanouski approved these changes

2024-09-22 12:19 UTC, merged