Homework 8 money
kessydy/Homework pull request #8
Opened 2024-10-13 10:47 UTC by kessydy

2024-10-15 07:34 UTC, PavelIvanouski requested changes

2024-10-15 07:34 UTC, PavelIvanouski commented on src/by/it_academy/homework8/money/Money.java
> +    public void compareMoney(Money money) {
для сравнения проще перевести все в копейки и просто сравнить полное значение копеек

2024-10-15 07:34 UTC, PavelIvanouski commented on src/by/it_academy/homework8/money/Money.java
> +    private String rubleCase;
зачем поля rubleCase, kopeckCase? можно просто сделать, чтобы printRuble() и printKopeck() возвращали слова с нужным окончанием

2024-10-15 07:34 UTC, PavelIvanouski commented on src/by/it_academy/homework8/airline/Aircraft.java
> +    public Aircraft(int passengersCapacity, double liftingСapacity) {
зачем второй конструктор? есть ситуации когда нужно создать объект с двумя параметрами без имени?

2024-10-15 07:34 UTC, PavelIvanouski commented on src/by/it_academy/homework8/airline/AirLine.java
> +    public void FindPlane(Aircraft o) {
тут можно сделать несколько методов для поиска летательного средства по различным параметрам   name,
   passengersCapacity, liftingСapacity.
 и чтобы эти методы не void возвращали, а Aircraft.

2024-10-16 09:26 UTC, kessydy commented on src/by/it_academy/homework8/airline/Aircraft.java
> +    public Aircraft(int passengersCapacity, double liftingСapacity) {
Я через усечённый конструктор создаю эталонный объект с необходимыми параметрами, с которым потом сравниваю технику аэрофлота).

2024-10-16 11:49 UTC, PavelIvanouski requested changes

2024-10-16 11:49 UTC, PavelIvanouski commented on src/by/it_academy/homework8/airline/AirLine.java
> +        Aircraft aircraftNeeded = new Aircraft("There is no right aircraft");
зачем создавать объект Aircraft и в имя записывать "There is no right aircraft"?
можно просто Aircraft aircraftNeeded = null например

2024-10-17 12:07 UTC, PavelIvanouski approved these changes

2024-10-17 12:25 UTC, merged